//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchMaster()
        {
            this.ExpenseVoucherMasters = new HashSet<ExpenseVoucherMaster>();
        }
    
        public int BID { get; set; }
        public string BatchName { get; set; }
        public string BatchCode { get; set; }
        public string BatchDesc { get; set; }
        public string BatchNo { get; set; }
        public string ATNo { get; set; }
        public string VechicleNo { get; set; }
        public string RecievedFrom { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<System.DateTime> MFGDate { get; set; }
        public Nullable<System.DateTime> EXPDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DepotID { get; set; }
        public Nullable<System.DateTime> Esl { get; set; }
        public Nullable<bool> IsSentto { get; set; }
        public string IsBatchStatus { get; set; }
        public Nullable<int> StockId { get; set; }
        public string ContactNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> CostOfParticular { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> WeightofParticular { get; set; }
        public string WeightUnit { get; set; }
        public string WarehouseNo { get; set; }
        public Nullable<decimal> SampleSentQty { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SectionRows { get; set; }
        public Nullable<int> SectionCol { get; set; }
    
        public virtual DepuMaster DepuMaster { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseVoucherMaster> ExpenseVoucherMasters { get; set; }
    }
}
