//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESLIssue
    {
        public int EslID { get; set; }
        public Nullable<int> BID { get; set; }
        public string IssueTo { get; set; }
        public string Quantitytype { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string RemarksBynurGP { get; set; }
        public string RemarksByjcoiGP { get; set; }
        public string RemarksByjDSO { get; set; }
        public string OverallRemarks { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> Addedby { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public Nullable<System.DateTime> RecievedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
