//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Descripition { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Addedby { get; set; }
        public Nullable<System.DateTime> Addedon { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> UndatedOn { get; set; }
        public Nullable<int> CommandId { get; set; }
    
        public virtual CommandMaster CommandMaster { get; set; }
    }
}
