//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForwardNoteMaster
    {
        public int Id { get; set; }
        public Nullable<int> batchId { get; set; }
        public string forwardingNoteNumber { get; set; }
        public Nullable<System.DateTime> forwardNoteDate { get; set; }
        public string officerDesignation { get; set; }
        public string officerPostalAddress { get; set; }
        public string addressee { get; set; }
        public string nomenStore { get; set; }
        public string containerType { get; set; }
        public string sampleRefNumber { get; set; }
        public string sampleIdentificationMarks { get; set; }
        public Nullable<decimal> sampleQualtity { get; set; }
        public Nullable<int> numberOfSamples { get; set; }
        public string sampleType { get; set; }
        public Nullable<System.DateTime> dispatchDate { get; set; }
        public string dispatchMethod { get; set; }
        public Nullable<System.DateTime> sampleDrawnDate { get; set; }
        public string drawerNameAndRank { get; set; }
        public Nullable<decimal> quantityRepressntedBySample { get; set; }
        public string intendedDestination { get; set; }
        public Nullable<System.DateTime> fillingDate { get; set; }
        public string iNoteNumber { get; set; }
        public Nullable<System.DateTime> iNoteDate { get; set; }
        public string previousTestReferences { get; set; }
        public string tankNumber { get; set; }
        public string containerMarkingDetails { get; set; }
        public string tradeOwned { get; set; }
        public string govtStock { get; set; }
        public string tradeGovtAccepted { get; set; }
        public string reasonForTest { get; set; }
        public string governingSupply { get; set; }
        public string atNoReferences { get; set; }
        public Nullable<int> isForwardingNoteActive { get; set; }
        public Nullable<System.DateTime> OldEslDate { get; set; }
        public Nullable<System.DateTime> EslModifyDate { get; set; }
    }
}
