//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatInOut
    {
        public int Id { get; set; }
        public Nullable<bool> IsLoadIn { get; set; }
        public string Recievedfrom { get; set; }
        public string vehbano { get; set; }
        public string franchiseeno { get; set; }
        public string ArmyNo { get; set; }
        public string rank { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> timein { get; set; }
        public string typeofvehicle { get; set; }
        public string unitQuantityTypeId { get; set; }
        public string loadin { get; set; }
        public string IdtId { get; set; }
        public Nullable<System.DateTime> timeout { get; set; }
        public string loadout { get; set; }
        public string stationDepuID { get; set; }
        public string stationUnitId { get; set; }
        public string fuelintankIn { get; set; }
        public string fuelintankOut { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
