//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDTStockTransfer
    {
        public int Id { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> IDTId { get; set; }
        public string PackingType { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Format { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<int> ToLooseCount { get; set; }
    }
}
