//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManuMgmt
    {
        public int Id { get; set; }
        public string ManuName { get; set; }
        public string ManuLink { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
