//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMCapacity
    {
        public int Id { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
