//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductMaster()
        {
            this.BatchMasters = new HashSet<BatchMaster>();
            this.ExpenseVoucherMasters = new HashSet<ExpenseVoucherMaster>();
            this.StockMasters = new HashSet<StockMaster>();
            this.tblLPCPs = new HashSet<tblLPCP>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Desc { get; set; }
        public string Short_Product_Desc { get; set; }
        public string Admin_Remarks { get; set; }
        public Nullable<decimal> product_cost { get; set; }
        public string Product_Code { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public string IsProductStatus { get; set; }
        public string Cat { get; set; }
        public string productUnit { get; set; }
        public Nullable<decimal> GSreservre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchMaster> BatchMasters { get; set; }
        public virtual CategoryMaster CategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseVoucherMaster> ExpenseVoucherMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMaster> StockMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLPCP> tblLPCPs { get; set; }
    }
}
