//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPakaging
    {
        public int Id { get; set; }
        public string PackagingType { get; set; }
        public int StockBatchId { get; set; }
        public decimal RemainingQty { get; set; }
        public string Format { get; set; }
    }
}
