//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockVehicle
    {
        public int Id { get; set; }
        public int StockID { get; set; }
        public string DriverName { get; set; }
        public string VehicleNo { get; set; }
        public int StockBatchId { get; set; }
        public decimal SentQty { get; set; }
        public decimal RecievedQty { get; set; }
        public string ChallanNo { get; set; }
        public string IsDDOrCHT { get; set; }
    }
}
