//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_idtQty_Quarter
    {
        public int id { get; set; }
        public Nullable<int> pid { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Qid { get; set; }
        public string QuarterRange { get; set; }
        public string dipu { get; set; }
        public Nullable<int> dipuid { get; set; }
        public Nullable<int> IDTqty { get; set; }
        public Nullable<int> left_IDTqty { get; set; }
        public Nullable<int> fyid { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    }
}
