//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vechileMaster_Type
    {
        public int VtypeId { get; set; }
        public string Vtypename { get; set; }
        public Nullable<int> Isactive { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<int> Createduserid { get; set; }
        public Nullable<int> ModifieduserId { get; set; }
    }
}
