//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductIDT_Quantity
    {
        public int id { get; set; }
        public Nullable<int> PID { get; set; }
        public string Product_Name { get; set; }
        public string Dipu { get; set; }
        public Nullable<int> Dipuprd_IDTqty { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    }
}
