//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Atttribute
    {
        public int TypeId { get; set; }
        public string AttributeName { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> CreateduserId { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> ModifieduserId { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
    }
}
