//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLPCP
    {
        public int ID { get; set; }
        public bool IsATNo { get; set; }
        public bool IsSONo { get; set; }
        public string ATSONo { get; set; }
        public int SupplierID { get; set; }
        public string SupplierContactNo { get; set; }
        public System.DateTime TenderDate { get; set; }
        public decimal LDPer { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public int OriginalMfgID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime DeliveryTime { get; set; }
        public decimal Rate { get; set; }
        public decimal Value { get; set; }
        public bool Status { get; set; }
        public bool Late { get; set; }
        public bool Dispute { get; set; }
        public bool Other { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int AddedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual OriginalManufacture_ OriginalManufacture_ { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
