//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuarter
    {
        public int QuarterId { get; set; }
        public string QuarterName { get; set; }
        public Nullable<int> QuarterYear { get; set; }
        public Nullable<int> QuarterRank { get; set; }
        public string YearRange { get; set; }
    }
}
