//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSection()
        {
            this.tblSection1 = new HashSet<tblSection>();
        }
    
        public int ID { get; set; }
        public string Section { get; set; }
        public string SubSection { get; set; }
        public Nullable<int> IsParent { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Col { get; set; }
        public Nullable<int> Drawers { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    
        public virtual tblWarehouse tblWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSection> tblSection1 { get; set; }
        public virtual tblSection tblSection2 { get; set; }
    }
}
