//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHPDNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int User_ID { get; set; }
        public string FirstName { get; set; }
        public string UserCode { get; set; }
        public string LastName { get; set; }
        public string User_Name { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Password { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Addedon { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> Modifiedon { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ArmyNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual RoleMaster RoleMaster { get; set; }
    }
}
